pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'        // Nom configuré dans "Global Tool Configuration"
        maven 'M2_HOME'        // Nom configuré dans "Global Tool Configuration"
    }

    stages {
        stage('Checkout') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    git branch: 'main',
                        url: "https://${GITHUB_TOKEN}@github.com/firasboudhraa/SpringBootProject.git"
                }
            }
        }

        stage('Build') {
            steps {
                dir('tpfoyer') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Maven Package') {
            steps {
                dir('tpfoyer') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage("Docker Build") {
            steps {
                dir('tpfoyer') {
                    sh 'docker build -t firasboudhraa/tpfoyer .'
                }
                sh 'docker images'
            }
        }

        stage("Docker Login") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'DOCKER_CREDENTIALS', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin'
                    }
                }
            }
        }

        stage("Docker Push") {
            steps {
                sh 'docker push firasboudhraa/tpfoyer'
            }
        }
    }

    post {
        success {
            echo "✅ Build succeeded, triggered by GitHub webhook!"
        }
        failure {
            echo "❌ Build failed, check logs!"
        }
    }
}
